name: pesantri
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  another_flutter_splash_screen: ^1.1.4
  syncfusion_flutter_charts: ^22.2.8
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_screenutil: 5.8.4
  dio: ^5.3.2
  intl: ^0.18.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/icons/
  uses-material-design: true
